### PR TITLE
Remove 2018 Strings

### PR DESCRIPTION
**Pull request by AndrewReitz**
Updating the project to be used for future pride events

### CODE REVIEW

**Comment by ebelinski** [comment]
Can you change the module name from `Twin-Cities-Pride-2018` to `Twin-Cities-Pride` too?

**Comment by AndrewReitz** [comment]
Where are you seeing that?

**Comment by ebelinski** [comment]
I think maybe I just didn't clean my project folder.

**Review by ebelinski — APPROVED** [review]
LGTM

**Pull request merged**
